apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: development
  namespace: kargo-a-go-go
  annotations:
    kargo.akuity.io/color: green
    kargo.akuity.io/argocd-context: '[{"name":"kargo-a-go-go-development","namespace":"argocd"}]'
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: plat-chart
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote