apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kargo-a-go-go
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  destinations:
  - name: '*'
    namespace: plat-*
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/pbrousseau-sdx/kargo-a-go-go.git
